CREATE DATABASE IF NOT EXISTS QuanLyBanHang;
USE QuanLyBanHang;

-- Bảng lưu danh sách khách hàng
CREATE TABLE IF NOT EXISTS Customer (
    cID INT AUTO_INCREMENT PRIMARY KEY,
    cName VARCHAR(100) NOT NULL,
    cAge TINYINT CHECK (cAge >= 0)
);

-- Bảng lưu thông tin hóa đơn mua hàng
CREATE TABLE IF NOT EXISTS `Order` (
    oID INT AUTO_INCREMENT PRIMARY KEY,
    cID INT NOT NULL,
    oDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    oTotalPrice DECIMAL(12, 2) DEFAULT NULL,
    FOREIGN KEY (cID) REFERENCES Customer(cID) ON UPDATE CASCADE ON DELETE RESTRICT
);

-- Bảng lưu danh sách sản phẩm
CREATE TABLE IF NOT EXISTS Product (
    pID INT AUTO_INCREMENT PRIMARY KEY,
    pName VARCHAR(150) NOT NULL,
    pPrice DECIMAL(12, 2) NOT NULL CHECK (pPrice >= 0)
);

-- Bảng lưu chi tiết từng mặt hàng trong hóa đơn
CREATE TABLE IF NOT EXISTS Orderdetail (
    oID INT NOT NULL,
    pID INT NOT NULL,
    odQTY INT NOT NULL CHECK (odQTY > 0),
    PRIMARY KEY (oID, pID),
    FOREIGN KEY (oID) REFERENCES `Order`(oID) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY (pID) REFERENCES Product(pID) ON UPDATE CASCADE ON DELETE RESTRICT
);